# Generated by Django 2.2.2 on 2019-06-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatormodel',
            name='ascvd_risk',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calculatormodel',
            name='bmi',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='calculatormodel',
            name='dm_risk',
            field=models.FloatField(null=True),
        ),
    ]
